---
title: "PCA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(glmnet)
library(magrittr)
library(dplyr)
library(lubridate)
library(purrr)
```

Data import
```{r}
data <- read_xlsx('stats.xlsx')
```

lubridate test
```{r echo=FALSE, eval=FALSE}
test <- "00:27:28"
test2 <- period_to_seconds(hms(test))

x <- "27:28"
y <- paste("00:", x, sep = "")
z <- period_to_seconds(hms(y))
typeof(z)
```

PCA

extract only numerical data
```{r}
# Convert min:sec to hour:min:sec to seconds
minToSec <- function(x) {
  toHms <- paste("00:",x,sep="")
  result <- period_to_seconds(hms(toHms))
  return(result)
}
# Apply to data
data_numeric <- data %>% select(c(1,3:22))
data_numeric[2] <- data_numeric[2] %>% map(minToSec)

# Make sure everything is numeric
data_numeric <- mutate_all(data_numeric, function(x) as.numeric(as.character(x)))

# PCA
dn_pca <- prcomp(data_numeric, center = TRUE, scale = TRUE)

# Graph results
screeplot(dn_pca, type = "l", npcs = 15, main = "Screeplot of the first 10 PCs")
abline(h = 1, col="red", lty=5)
legend("topright", legend=c("Eigenvalue = 1"),
       col=c("red"), lty=5, cex=0.6)

plot(dn_pca$x[,1],dn_pca$x[,2], main = "PC1 / PC2 - plot")

```


