---
title: "Data Exploration"
output: html_notebook
---

```{r setup, include=FALSE}
library(magrittr)
library(ggplot2)
library(hrbrthemes)
library(viridis)
library(forcats)
library(tidyr)
```


```{r, echo=FALSE}
# import data
xd <- read.csv('../data/statsNumeric.csv')
```

```{r}

#test
data <- read.table("https://raw.githubusercontent.com/zonination/perceptions/master/probly.csv", header=TRUE, sep=",")
data <- data %>%
  gather(key="text", value="value") %>%
  mutate(text = gsub("\\.", " ",text)) %>%
  mutate(value = round(as.numeric(value),0))
```

```{r}
# plot test
p <- data %>%
  mutate(text = fct_reorder(text, value)) %>%
  ggplot( aes(x=value, color=text, fill=text)) +
    geom_histogram(alpha=0.6, binwidth = 5) +
    scale_fill_viridis(discrete=TRUE) +
    scale_color_viridis(discrete=TRUE) +
    theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    ) +
    xlab("") +
    ylab("Assigned Probability (%)") +
    facet_wrap(~text)
```

```{r}
# plot
# x <- xd %>% 
#   ggplot(aes(x=))
  
```

