---
title: "umap"
output: html_document
date: '2022-06-15'
---

```{r setup, include=FALSE}
library(tidyverse)
library(umap)
```

```{r}
df <- read_csv('../data/stats_numeric_R.csv')
```

```{r}

df <- read_csv('../data/stats_numeric_R.csv')

pts_to_quantile <- function(x) {
  q <- quantile(df$PTS)
  if((x >= q[1]) & (x < q[2])) {
    return(1)
  } else if ((x >= q[2]) & (x < q[3])) {
    return(2)
  } else if ((x >= q[3]) & (x < q[4])) {
    return(3)
  } else if ((x >= q[4]) & (x <= q[5])) {
    return(4)
  }
}

df.labels <- apply(df["PTS"], MARGIN = 1, FUN=pts_to_quantile)

df <- subset(df, select=-PTS)

df.umap = umap(df)

umap_df <- df.umap$layout %>%
  as.data.frame()%>%
  rename(UMAP1="V1",
         UMAP2="V2") %>%
  mutate(ID=row_number())

umap_df %>%
  ggplot(aes(x = UMAP1, 
             y = UMAP2, 
             color = df.labels))+
  geom_point()+
  labs(x = "UMAP1",
       y = "UMAP2",
      subtitle = "UMAP plot")

```

```{r}

df["FP"] <- df["PTS"] + 1.25 * df["REB"] + 0.5 * df["3PM"] + 1.5 * df["AST"] + 
  2* df["STL"] + 2 * df["BLK"] - 0.5 * df["TO"]


```


```{r}
```

